version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "4000:4000"
    links:
      - redis
  web:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
